name: real_volume
description: A Flutter audio/volume plugin which provides easy access to volume/audio related info.
version: 1.0.6
homepage: https://github.com/Pana-g/real_volume.git
issue_tracker: https://github.com/Pana-g/real_volume/issues?q=is%3Aissue+is%3Aopen

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.fubigemo.real_volume
        pluginClass: RealVolumePlugin
      ios:
        pluginClass: RealVolumePlugin

